export enum DatabaseErrorCode {
  CONNECTION_ERROR = "DB_CONNECTION_ERROR",
  QUERY_FAILED = "DB_QUERY_FAILED",
  CONSTRAINT_VIOLATION = "DB_CONSTRAINT_VIOLATION",
  TRANSACTION_FAILED = "DB_TRANSACTION_FAILED",
}
